image: lehung/jira:7.12.3
clone:
  depth: full

pipelines:
  custom:
    create-release-base-7:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-7
            - export BASE_VERSION=7
            - export DOCKER_REPO=lehungio/jira
            - export DOCKERFILE_VERSION_STRING=JIRA_VERSION
            - export GIT_USER=pipelinesagent
            - export GIT_EMAIL=pipelines-agent@atlassian.com
            - export MAC_PRODUCT_KEY=jira-software
            - python /usr/src/app/create_release.py
  branches:
    base-7:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-7
            - export BASE_VERSION=7
            - export DOCKER_REPO=lehungio/jira
            - export DOCKERFILE_VERSION_STRING=JIRA_VERSION
            - export GIT_USER=pipelinesagent
            - export GIT_EMAIL=pipelines-agent@atlassian.com
            - export MAC_PRODUCT_KEY=jira-software
            - python /usr/src/app/update_release.py